PODCAST_NAME: "The 50 Shades of Beer Podcast"
PODCAST_LINK: "https://podcast.xandermar.com"
PODCAST_DESCRIPTION: "A conversational podcast covering current events, trending topics, opinions, and reviews."
CURRENT_YEAR: "2026"
GENERATOR: "XDM Podcast AI"
PODCAST_EMAIL: "podcast@xandermar.com"
PODCAST_LOCATION: "Milton, Delaware, United States"
ITUNES_TYPE: "episodic"